### ISSUE TITLE
Collection State check throws an ValueError when trying to convert string 'options.warning' to floar 

### ISSUE THREAD

**Issue by emanuel281** [mzupan/nagios-plugin-mongodb#205]
$USER1$/nagios-plugin-mongodb/check_mongodb.py -H $HOSTADDRESS$ -A $ARG1$ -P $ARG2$ -W $ARG3$ -C $ARG4$

File "./check_mongodb.py", line 1571, in <module>
    sys.exit(main(sys.argv[1:]))
  File "./check_mongodb.py", line 167, in main
    warning = float(options.warning or 0)
ValueError: could not convert string to float: dmp

**Comment by mzupan** [comment]
that seems like your nagios config might be wrong since its getting `dmp` in for the `-W` flag?

```
>>> float("dmp" or 0)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: could not convert string to float: dmp
```

**Comment by aNerdInTheHand** [comment]
I had this same issue, caused because `collection_state` does not require a warning or critical flag, but in the example it is called as the first parameter of `check_mongo_db`, which does require warning and critical flags. My workaround was to just create the following new command:
```
define command {
        command_name check_mongodb_colstate
        command_line $USER1$/nagios-plugin-mongodb/check_mongodb.py -H $HOSTADDRESS -A $ARG1$ -P $ARG2$ -d $ARG3$ -c $ARG4$
}
```

Then call this like so:
```
define service{
       use                             local-service
       host_name                       xxx
       service_description            xxx
       contacts                        nagiosadmin
       check_command   check_mongodb_colstate!collection_state!27017!dbname!collectionname
}
```
